name: CI/CD
on: push
jobs:
  deploy:
    name: Deploy on npm
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master' # Deploy only on the master branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
